export const styles = {
  layout: { display: 'flex', height: '100vh', background: '#F4F1EA', position: 'relative', overflow: 'hidden' },
  icon: { cursor: 'pointer', transition: 'color 0.2s', position: 'relative' },
  /** Default: legacy full-viewport main height. Merged workspace overrides with flex + height:auto in JSX. */
  content: { flex: 1, display: 'flex', flexDirection: 'column', transition: 'margin-left 0.3s ease', height: '100vh', overflowY: 'auto', overflowX: 'hidden' },
  avatarOptionSelected: { background: 'white', border: '2px solid #4CAF50', boxShadow: '0 0 0 3px rgba(76, 175, 80, 0.1)' },
  addBtn: { background: '#4CAF50', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 'bold' },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.28)', backdropFilter: 'none', WebkitBackdropFilter: 'none', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 2000 },
  modal: { background: 'white', padding: '24px', borderRadius: '20px', width: '360px', maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)', zIndex: 10000, position: 'relative' },
  badge: { position: 'absolute', top: '-5px', right: '-5px', background: '#FF5252', color: 'white', width: '18px', height: '18px', borderRadius: '50%', fontSize: '11px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' },
  header: {
    background: 'rgba(255, 255, 255, 0.8)',
    backdropFilter: 'blur(20px)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    maxWidth: 'none',
    marginLeft: '0',
    width: '100%',
    borderRadius: '24px',
    border: '1px solid rgba(226, 232, 240, 0.8)',
    boxSizing: 'border-box',
    zIndex: 10
  },
  actionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 28px',
    background: 'linear-gradient(135deg, #6366F1 0%, #a855f7 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '18px',
    cursor: 'pointer',
    width: '92%', height: '92%',
    fontWeight: '800',
    fontSize: '14px',
    letterSpacing: '0.5px',
    boxShadow: '0 10px 20px -5px rgba(99, 102, 241, 0.4)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    transform: 'translateY(0)',
    justifyContent: 'center',
  },
  gridMenu: {
    position: 'absolute',
    top: '56px',
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'rgba(255, 255, 255, 0.98)',
    backdropFilter: 'blur(8px)',
    borderRadius: '12px',
    padding: '8px',
    boxShadow: '0 12px 30px rgba(0,0,0,0.08)',
    zIndex: 99999,
    minWidth: '180px',
    border: '1px solid rgba(0,0,0,0.04)'
  },
  gridOption: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    textAlign: 'left',
    padding: '10px 12px',
    marginBottom: '6px',
    borderRadius: '10px',
    cursor: 'pointer',
    border: 'none',
    background: 'transparent',
    fontWeight: '800',
    color: '#475569',
    fontSize: '13px',
    transition: 'all 0.16s ease'
  },
};
